version: '3.9'
name: "video-loader"

services:
  app:
    ports:
      - "50051:50051"
    env_file:
      - config/.env
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "2G"
        max-file: "1"
    networks:
      video-loader-network:

networks:
  video-loader-network:
    name: video-loader-network
